from .CurrentLyricWidget import CurrentLyricWidget
from .TreeLyricsWidget import TreeLyricsWidget
from .LyricsWidget import LyricsWidget
from .TreeSelectedLyricsWidget import TreeSelectedLyricsWidget
from .SelectedListLyricsWidget import SelectedListLyricsWidget
from .CameraWidget import CameraWidget
